services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8.24.21
    restart: unless-stopped
    networks:
      - acepanel-network
    ports:
      - "${CLICKHOUSE_PORT_HTTP}:8123"
      - "${CLICKHOUSE_PORT_TCP}:9000"
      - "${CLICKHOUSE_PORT_REPLICATION}:9009"
    environment:
      - TZ=${CLICKHOUSE_TIME_ZONE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./data/logs:/var/log/clickhouse-server
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8123/ping || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  acepanel-network:
    external: true
